@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mcmoddev.mmdbench.automatic;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;
